### PR TITLE
Update vulscan to support newer versions of Nmap

### PR DESCRIPTION
**Pull request by Jarnhei**
Added stringaux library and changed stdnse.strsplit functions to stingaux.strsplit

### CODE REVIEW

**Comment by shawneric** [comment]
Just as an FYI, when I cloned this, it did not update this change. Please merge correctly so that when people clone vulscan they get the correct updated files. Thanks!

**Comment by Jarnhei** [comment]
> Just as an FYI, when I cloned this, it did not update this change. Please merge correctly so that when people clone vulscan they get the correct updated files. Thanks!
Thanks for reporting, changes are now merged to my main repository

**Comment by marcruef** [comment]
Thanks for the contribution. When I am running Nmap 7.x on Windows it does not work. I'd like to see full compatibility for Windows too.

> C:\Program Files (x86)\nmap-7.70>nmap -sV -p80 --script=vulscan scanme.nmap.org
> WARNING: Could not import all necessary Npcap functions. You may need to upgrade to the latest version from http://www.npcap.org. Resorting to connect() mode -- Nmap may not function completely
> Starting Nmap 7.70 ( https://nmap.org ) at 2019-09-19 09:59 W. Europe Daylight Time
> NSE: Failed to load C:\Program Files (x86)\nmap-7.70/scripts\vulscan/vulscan.nse:
> ...rogram Files (x86)\nmap-7.70/scripts\vulscan/vulscan.nse:215: module 'stringaux' not found:
>         NSE failed to find nselib/stringaux.lua in search paths.
>         no field package.preload['stringaux']
>         no file 'C:\Program Files (x86)\nmap-7.70\lua\stringaux.lua'
>         no file 'C:\Program Files (x86)\nmap-7.70\lua\stringaux\init.lua'
>         no file 'C:\Program Files (x86)\nmap-7.70\stringaux.lua'
>         no file 'C:\Program Files (x86)\nmap-7.70\stringaux\init.lua'
>         no file 'C:\Program Files (x86)\nmap-7.70\..\share\lua\5.3\stringaux.lua'
>         no file 'C:\Program Files (x86)\nmap-7.70\..\share\lua\5.3\stringaux\init.lua'
>         no file '.\stringaux.lua'
>         no file '.\stringaux\init.lua'
>         no file 'C:\Program Files (x86)\nmap-7.70\stringaux.dll'
>         no file 'C:\Program Files (x86)\nmap-7.70\..\lib\lua\5.3\stringaux.dll'
>         no file 'C:\Program Files (x86)\nmap-7.70\loadall.dll'
>         no file '.\stringaux.dll'
> stack traceback:
>         [C]: in function 'require'
>         ...rogram Files (x86)\nmap-7.70/scripts\vulscan/vulscan.nse:215: in function <...rogram Files (x86)\nmap-7.70/scripts\vulscan/vulscan.nse:1>
> NSE: failed to initialize the script engine:
> C:\Program Files (x86)\nmap-7.70/nse_main.lua:619: could not load script
> stack traceback:
>         [C]: in function 'error'
>         C:\Program Files (x86)\nmap-7.70/nse_main.lua:619: in field 'new'
>         C:\Program Files (x86)\nmap-7.70/nse_main.lua:836: in local 'get_chosen_scripts'
>         C:\Program Files (x86)\nmap-7.70/nse_main.lua:1315: in main chunk
>         [C]: in ?
> 
> QUITTING!

**Comment by Jarnhei** [comment]
> Thanks for the contribution. When I am running Nmap 7.x on Windows it does not work. I'd like to see full compatibility for Windows too.
> 
> > C:\Program Files (x86)\nmap-7.70>nmap -sV -p80 --script=vulscan scanme.nmap.org

Hi, update your nmap to 7.80. I tested this on windows and it worked without any problems on nmap version 7.80.

**Comment by marcruef** [comment]
Thanks for your feedback. I was able to implement support for older Nmap versions <=7.70 and newer >7.80 with commit https://github.com/scipag/vulscan/commit/50a1480f670288d80bd668c6264ff06891f08a98

**Pull request closed without merging**
